language: node_js
node_js: '0.10'
install:
- npm install --quiet
script:
- npm run lint
- npm run test
deploy:
  provider: npm
  email: elmerbulthuis@gmail.com
  api_key:
    secure: 1iK+yz3jPyxad31Hjs+jqBZ7IsreiztgyE4K79MKC5lC+pv1yY00ZLzRDzt7P5JX1PsnAz3W63Fay8hpS4L7qydPuJQT8MnjDuATpKixRvkE2dl7nSpdq18PYbYscBCeAF8pIVRgEmAQmzUjLD/8kj8Q1fRw43qT2UNoDqppVf67ZLfoXbALiWpW6Pjk9fOUB1sXOyFJKDLC5pHtNZgyUFHrwQ1zVDoh3naSOVXyEWBYuj6SOCHJYquXCY4acKrvC28im/0evi/6CpyFaI1Ru8xoKVQ43nFtRM9Lc7Wy/gLn83mj870f2vL6SXGZQkmFVbjRM1VABmYrtl1DjyhI0XEWW1judM85Ywa7QWghtCSn8CkWG8K+GJtizZY9sFxjBOm19tymC9w0yaL6ImDO225U3MkIw86x4WAnxElVU3JzJi7YPxUeZ41bC8Yx/3xRgmyeOcX2leseL6tzZeTsIklKwMacZOfDXo6ANUv2bCKona1OhU10FxUYt9SfUOOAv17n/LTkPNjbREjUoz/HwDb54+Mn5WZIS8zKpP0WZXYBdTFrFANHJHYUJNV7FlS4M0ZEaorGUHTFX45GSNgf+kLaGwxs7BaUI8aSkb6MPzK6MJs/uj7eV3tA/8nZb04CIdTVwAK3jBWvIgxnINcb7SH5lvd1B4Qj2QLS4mTjtP8=
